AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Athletes to College Portal
Globals:
  Function:
    Runtime: python3.7
    Timeout: 30
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-729d3814
  CognitoDomain:
    Type: String
    Default: thefirmu
  AdminCognitoDomain:
    Type: String
    Default: thefirmu-admin
  ContentUrl:
    Type: String
    Default: "https://devportal.thefirmu.org"
  AdminContentUrl:
    Type: String
    Default: "https://adminportal.thefirmu.org"
Mappings:
  VPC2Subnet:
    vpc-729d3814:
      Subnets:
        - "subnet-76ade63f"
        - "subnet-8c44d6d7"
        - "subnet-be65cf82"
Resources:
  LambdaForCloudFormation:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: LambdaForCloudFormation
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Action: 'sts:AssumeRole'
            Principal:
              Service: lambda.amazonaws.com
      Policies:
        -
          PolicyName: WriteCloudWatchLogs
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              -
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
        -
          PolicyName: UpdateUserPoolClient
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              -
                Effect: Allow
                Action: 'cognito-idp:UpdateUserPoolClient'
                Resource: 'arn:aws:cognito-idp:*:*:userpool/*'
        -
          PolicyName: ManageUserPoolDomain
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              -
                Effect: Allow
                Action: 'cognito-idp:CreateUserPoolDomain'
                Resource: 'arn:aws:cognito-idp:*:*:userpool/*'
              -
                Effect: Allow
                Action: 'cognito-idp:DeleteUserPoolDomain'
                Resource: 'arn:aws:cognito-idp:*:*:userpool/*'
              -
                Effect: Allow
                Action: 'cognito-idp:DescribeUserPoolDomain'
                Resource: '*'
        -
          PolicyName: InvokeLambdaFunction
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              -
                Effect: Allow
                Action: 'lambda:InvokeFunction'
                Resource: 'arn:aws:lambda:*:*:function:*'
  CloudFormationSendResponse:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: CloudFormationSendResponse
      Runtime: nodejs8.10
      Code: ./CloudFormationSendResponse
      Handler: index.handler
      Role: !GetAtt LambdaForCloudFormation.Arn
  CloudFormationCognitoUserPoolClientSettings:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: CloudFormationCognitoUserPoolClientSettings
      Runtime: nodejs8.10
      Code: ./CloudFormationCognitoUserPoolClientSettings.js
      Handler: CloudFormationCognitoUserPoolClientSettings.handler
      Role: !GetAtt LambdaForCloudFormation.Arn
    DependsOn: CloudFormationSendResponse
  CloudFormationCognitoUserPoolDomain:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: CloudFormationCognitoUserPoolDomain
      Runtime: nodejs8.10
      Code: ./CloudFormationCognitoUserPoolDomain.js
      Handler: CloudFormationCognitoUserPoolDomain.handler
      Role: !GetAtt LambdaForCloudFormation.Arn
    DependsOn: CloudFormationSendResponse
  theFirmuAdminCognitoPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
         AllowAdminCreateUserOnly: True
         InviteMessageTemplate:
           EmailMessage: "Welcome to The Firmu Admin!  Below you will find your username and temporary password.  Please go to https://adminportal.thefirmu.org to change your password.\n\nYour username is {username} and temporary password is {####}. \n\nThank you for being a member of The FirmU!"
           EmailSubject: "Welcome to The FirmU Admin!"
      AutoVerifiedAttributes:
        - email
      DeviceConfiguration:
        ChallengeRequiredOnNewDevice: False
        DeviceOnlyRememberedOnUserPrompt: False
      EmailConfiguration:
        EmailSendingAccount: DEVELOPER
        ReplyToEmailAddress: admin@thefirmu.org
        SourceArn: !Join ['',['arn:aws:ses:',!Ref "AWS::Region",':',!Ref "AWS::AccountId",':identity/admin@thefirmu.org']]
      EmailVerificationMessage: "Your FirmU verification code is {####}. Please go to https://adminportal.thefirmu.org"
      EmailVerificationSubject: "Your FirmU verification code"
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: True
          RequireNumbers: True
          RequireSymbols: True
          RequireUppercase: True
          TemporaryPasswordValidityDays: 7
      Schema:
        - AttributeDataType: String
          Mutable: True
          Name: email
          Required: True
      UserPoolName: "thefirmu-admin"
  theFirmuAdminCognitoClientSettings:
    Type: 'Custom::CognitoUserPoolClientSettings'
    Properties:
      ServiceToken: !GetAtt CloudFormationCognitoUserPoolClientSettings.Arn
      UserPoolId: !Ref theFirmuAdminCognitoPool
      UserPoolClientId: !Ref theFirmuAdminCognitoClient
      SupportedIdentityProviders:
        - COGNITO
      CallbackURL: !Join ['',[!Ref AdminContentUrl,',https://',!GetAtt ['LoadBalancer','DNSName'],'/oauth2/idpresponse,',!Ref AdminContentUrl,'/oauth2/idpresponse,https://',!GetAtt ['LoadBalancer','DNSName']]]
      LogoutURL: !Ref AdminContentUrl
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
  theFirmuAdminDomain:
    Type: 'Custom::CognitoUserPoolDomain'
    Properties:
      ServiceToken: !GetAtt CloudFormationCognitoUserPoolDomain.Arn
      UserPoolId: !Ref theFirmuAdminCognitoPool
      Domain: !Ref AdminCognitoDomain
  theFirmuCognitoPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
         AllowAdminCreateUserOnly: True
         InviteMessageTemplate:
           EmailMessage: "Welcome to The Firmu!  Below you will find your username and temporary password.  Please go to https://devportal.thefirmu.org to change your password.\n\nYour username is {username} and temporary password is {####}. \n\nThank you for being a member of The FirmU!"
           EmailSubject: "Welcome to The FirmU!"
      AutoVerifiedAttributes:
        - email
      DeviceConfiguration:
        ChallengeRequiredOnNewDevice: False
        DeviceOnlyRememberedOnUserPrompt: False
      EmailConfiguration:
        EmailSendingAccount: DEVELOPER
        ReplyToEmailAddress: admin@thefirmu.org
        SourceArn: !Join ['',['arn:aws:ses:',!Ref "AWS::Region",':',!Ref "AWS::AccountId",':identity/admin@thefirmu.org']]
      EmailVerificationMessage: "Your FirmU verification code is {####}. Please go to https://devportal.thefirmu.org"
      EmailVerificationSubject: "Your FirmU verification code"
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: True
          RequireNumbers: True
          RequireSymbols: True
          RequireUppercase: True
          TemporaryPasswordValidityDays: 7
      Schema:
        - AttributeDataType: String
          Mutable: True
          Name: email
          Required: True
      UserPoolName: "thefirmu"
  theFirmuCognitoClientSettings:
    Type: 'Custom::CognitoUserPoolClientSettings'
    Properties:
      ServiceToken: !GetAtt CloudFormationCognitoUserPoolClientSettings.Arn
      UserPoolId: !Ref theFirmuCognitoPool
      UserPoolClientId: !Ref theFirmuMgmtCognitoClient
      SupportedIdentityProviders:
        - COGNITO
      CallbackURL: !Join ['',[!Ref ContentUrl,',https://',!ImportValue 'a2c-stack-LBDnsName','/oauth2/idpresponse,',!Ref ContentUrl,'/oauth2/idpresponse,https://',!ImportValue 'a2c-stack-LBDnsName']]
      LogoutURL: !Ref ContentUrl
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
  theFirmuDomain:
    Type: 'Custom::CognitoUserPoolDomain'
    Properties:
      ServiceToken: !GetAtt CloudFormationCognitoUserPoolDomain.Arn
      UserPoolId: !Ref theFirmuCognitoPool
      Domain: !Ref CognitoDomain
  theFirmuDynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "username"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: "thefirmu_user_info"
  theFirmuMgmtCognitoClient:
    Type: AWS::Cognito::UserPoolClient
    Properties: 
      ClientName: mgmt
      ExplicitAuthFlows: 
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: True
      RefreshTokenValidity: 30
      UserPoolId: !Ref theFirmuCognitoPool
  theFirmuAdminCognitoClient:
    Type: AWS::Cognito::UserPoolClient
    Properties: 
      ClientName: mgmt
      ExplicitAuthFlows: 
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: True
      RefreshTokenValidity: 30
      UserPoolId: !Ref theFirmuAdminCognitoPool
  cognitoPoolSSM:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: /a2c/dev/cognito_pool
      Type: String
      Value: !Ref theFirmuCognitoPool
  cognitoAdminPoolSSM:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: /a2c/dev/admin_cognito_pool
      Type: String
      Value: !Ref theFirmuAdminCognitoPool
  cognitoClientIdSSM:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: /a2c/dev/mgmt_cognito_client_id
      Type: String
      Value: !Ref theFirmuMgmtCognitoClient
  cognitoAdminClientIdSSM:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: /a2c/dev/admin_cognito_client_id
      Type: String
      Value: !Ref theFirmuAdminCognitoClient
  cognitoAuthUrlSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /a2c/dev/cognito_auth_url
      Type: String
      Value: !Join ['',['https://',!Ref CognitoDomain,'.auth.us-east-1.amazoncognito.com/oath2/']]
  cognitoAdminAuthUrlSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /a2c/dev/admin_cognito_auth_url
      Type: String
      Value: !Join ['',['https://',!Ref AdminCognitoDomain,'.auth.us-east-1.amazoncognito.com/oath2/']]
  cognitoContentUrlSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /a2c/dev/content_url
      Type: String
      Value: !Ref ContentUrl
  cognitoAdminContentUrlSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /a2c/dev/admin_content_url
      Type: String
      Value: !Ref AdminContentUrl
  dynamoDBTableNameSSM:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: /a2c/dev/table_name
      Type: String
      Value: !Ref theFirmuDynamoDBTable
  mgmtPortalCognitoPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "thefirmu.cognito.allow"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        -
          Effect: Allow
          Action: ['cognito-idp:AdminInitiateAuth', 'cognito-idp:AdminCreateUser']
          Resource: !GetAtt ['theFirmuCognitoPool','Arn']
      Roles:
        - !Ref "mgmtPortalRole"
  mgmtPortalDynamoPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "thefirmu.dynamodb.allow"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        -
          Effect: Allow
          Action: [ "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:GetItem",
                "dynamodb:Scan",
                "dynamodb:Query",
                "dynamodb:UpdateItem"
          ]
          Resource: !GetAtt [theFirmuDynamoDBTable,'Arn']
      Roles:
        - !Ref "mgmtPortalRole"
  mgmtPortalSSMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "thefirmu.ssm.allow"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        -
          Effect: Allow
          Action: ['ssm:GetParameter']
          Resource: !Join ['',['arn:aws:ssm:',!Ref 'AWS::Region',':',!Ref 'AWS::AccountId',':parameter/a2c/*']]
      Roles:
        - !Ref "mgmtPortalRole"
  mgmtPortalRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: a2c-mgmt-role
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Statement:
        -
          Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: ['sts:AssumeRole']
  mgmtPortalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: mgmt_handler.mgmt_handler
      CodeUri: ./mgmt/
      Role: !GetAtt ["mgmtPortalRole","Arn"]
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing 
      Subnets: !FindInMap [VPC2Subnet, !Ref "VpcId", Subnets]
      SecurityGroups:
      - !Ref LoadBalancerSecurityGroup
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: LambdaInvokePermission
    Properties:
      TargetType: lambda
      Targets:
      - Id: !GetAtt mgmtPortalFunction.Arn
  HttpsListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
      - TargetGroupArn: !Ref TargetGroup
        Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Certificates: 
      - CertificateArn: 'arn:aws:acm:us-east-1:530317771161:certificate/457def3f-75de-447d-90a5-96af2c6690db'
      Port: 443
      Protocol: HTTPS
  CognitoAdminListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    DependsOn: 
      - theFirmuAdminDomain
      - theFirmuAdminCognitoClientSettings
    Properties: 
      Actions: 
        - Type: authenticate-cognito
          AuthenticateCognitoConfig:
            UserPoolArn: !GetAtt  ['theFirmuAdminCognitoPool','Arn']
            UserPoolClientId: !Ref theFirmuAdminCognitoClient
            UserPoolDomain: "thefirmu-admin"
          Order: 1
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
          Order: 2
      Conditions: 
        - Field: path-pattern
          Values: [ "/" ]
      ListenerArn: !Ref HttpsListener
      Priority: 1
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt mgmtPortalFunction.Arn
      Action: 'lambda:InvokeFunction'
      Principal: elasticloadbalancing.amazonaws.com
Outputs:
  DynamoDBArn:
    Description: ARN of the Dynamo DB table
    Value: !GetAtt ["theFirmuDynamoDBTable","Arn"]
    Export:
      Name: !Sub "${AWS::StackName}-DynamoDBARN"
  CognitoPoolArn:
    Description: ARN of the Cognito Pool
    Value: !GetAtt ["theFirmuCognitoPool","Arn"]
    Export:
      Name: !Sub "${AWS::StackName}-CognitoPoolARN"
  CognitoPoolId:
    Description: ID of the Cognito Pool
    Value: !Ref "theFirmuCognitoPool"
    Export:
      Name: !Sub "${AWS::StackName}-CognitoPoolId"
